---
apiVersion: v1
kind: Service
metadata:
  name: distira-core
  labels:
    app: distira-core
spec:
  type: ClusterIP
  selector:
    app: distira-core
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
